sudo: required

language: go

# Versions of go that are explicitly supported by gonum.
go:
 - 1.6.x
 - 1.7.x
 - 1.8.x

go_import_path: gonum.org/v1/netlib

os:
 - linux
 - osx

env:
  matrix:
  - BLAS_LIB=OpenBLAS
  # Does not currently link correctly.  Note that there is an issue with drotgm in ATLAS.
  # - BLAS_LIB=ATLAS
  # If we can get multiarch builds on travis.
  # There are some issues with the Accellerate implementation.
  #- BLAS_LIB=Accellerate

matrix:
 exclude:
  - os: linux
    env: BLAS_LIB=Accelerate
  - os: linux
    env: BLAS_LIB=ATLAS
  - os: osx
    env: BLAS_LIB=ATLAS
  - os: osx
    env: BLAS_LIB=OpenBLAS

# Cache used to persist the compiled BLAS library between CI calls.
cache:
  directories:
  - .travis/OpenBLAS.cache

# Install the appropriate blas library (if any) and associated gonum software.
install:
 - source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/install.sh

script:
 - source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/test.sh
 - test -z "$(gofmt -d .)"
 # This is run last since it alters the tree.
 - ${TRAVIS_BUILD_DIR}/.travis/check-generate.sh
